name: CurosActs

on: [push]

jobs:
  Test1:
    runs-on: ubuntu-latest

    steps:
    - name: prueba1
      run: echo "TEST CORRECTO"
  
  Test2:
    runs-on: ubuntu-latest

    steps:
    - name: prueba2
      run: echo "TEST 2 CORRECTO"

  TrabajoTest2:
    runs-on: ubuntu-latest
    needs: Test1
    steps:
    - name: prueba1
      run: echo "Trabajo Correcto"
